version: "3.2"
services:
  nginx:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 8000:8000
    depends_on:
      - flask
      - front
      - sockets
  flask:
    build: .
    volumes:
      - '.:/app/src'
      - './static:/app/src/static'
    command: python /app/src/app.py
  celery:
    build: .
    volumes:
      - '.:/app/src'
    command: bash -c "cd /app/src && celery -A config worker"
    depends_on:
      - redis
      - sockets
  redis:
    image: redis:latest
  sockets:
    build: socket_server/.
  front:
    build:
      dockerfile: Front
      context: .
    volumes:
      - './static:/app'
    command: bash -c "cd /app/js && npm i && ng build --watch"
